baseURL = "http://www.hpc.ucdavis.edu"
languageCode = "en-us"
title = "High-Performance Computing @ UCDavis"
theme = "mainroad"
publishDir = "docs"
[Params]
subtitle = "Campus supercomputing resources"
description = "HPC @ UCDavis"
opengraph = false
twitter_cards = true
readmore = false
authorbox = true
toc = false
post_navigation = true
postSections = ["post","blog","news"]
customCSS = ["css/custom.css"]



[Author]
name = "HPC Admins"
bio = "The HPC @ UCD Administration and Support Team"

[Params.sidebar]
home = "right"
list = "left"
single = "false"
widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)


[menu]
  [[menu.main]]
     identifier = "1home"
     name = "home"
     url  = "http://www.hpc.ucdavis.edu"
     weight = 100

  [[menu.main]]
     identifier = "wiki"
     name = "CSE wiki"
     url  = "http://wiki.cse.ucdavis.edu"

